sudo: required
os: osx
language: ruby
rvm:
  - "2.5.0"
  - "2.5.1"
env:
  - "PGVERSION=9.5.0-1-linux-x64 PATH=\"/opt/PostgreSQL/9.5/bin:$PATH\""
  - "PGVERSION=9.1.19-3-linux-x64 PATH=\"/opt/PostgreSQL/9.1/bin:$PATH\""
  - "PGCROSS=true"
addons:
  postgresql: "9.5"
matrix:
  # Test cross compilation only with 2.3
  exclude:
    - rvm: "2.2"
      env: "PGCROSS=true"
    - rvm: "2.5.0"
      env: "PGCROSS=true"
    - rvm: "2.5.1"
      env: "PGCROSS=true"
    - rvm: rbx
      env: "PGCROSS=true"
  allow_failures:
      # one test fails because GVL unblocking function is not called by Rubinius core
    - rvm: rbx
before_install:
  - gem install bundler
  - bundle install
script: |
  if [ -z "$PGCROSS" ]; then
    rake compile test
  else
    rake gem:windows
  fi
